In [ ]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [ ]:
Yes, there is a difference in the data type of variables list_ and array_list.

Code to print the data types of both variables:

print(type(list_))
print(type(array_list))

In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [ ]:
for element in list_:
    print(type(element))

for element in array_list:
    print(type(element))

In [ ]:
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

In [ ]:
Yes, there will be a difference in the data type of the elements present in both the variables, `list_` and `array_list`. 

Initially, the data type of the elements in `list_` was strings, however, after creating the array `array_list` with dtype as 'int', the data type of the elements in the `array_list` will be integers.

To print the data types of each and every element present in both the variables, we can use the below code:

for element in list_:
    print(element, type(element))

for element in array_list:
    print(element, type(element))

The output will be as follows (assuming that the `list_` was initially defined as `[ '1' , '2' , '3' , '4' , '5' ]` and `array_list` was created as `array_list = np.array(object = list_, dtype = int)`):
```
1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>
1 <class 'int'>
2 <class 'int'>
3 <class 'int'>
4 <class 'int'>
5 <class 'int'>
``` 



In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [1]:
import numpy as np
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [2]:
import numpy as np
zeros_array = np.zeros((3, 3))

print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [3]:
import numpy as np
identity_matrix = np.identity(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
